# Generated by Django 6.0.5 on 2026-05-27 20:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in URLs and file paths', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reporting_year_start', models.DateField(blank=True, null=True)),
                ('reporting_year_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_analyst', models.BooleanField(default=False, help_text='Can review and approve records')),
                ('is_uploader', models.BooleanField(default=False, help_text='Can upload source files')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='ingestion.tenant')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fuel_stationary', 'Fuel — Stationary Combustion'), ('fuel_mobile', 'Fuel — Mobile Combustion'), ('procurement', 'Procurement (non-energy goods)'), ('electricity', 'Purchased Electricity'), ('heat_steam', 'Purchased Heat / Steam'), ('travel_air', 'Business Travel — Air'), ('travel_hotel', 'Business Travel — Hotel'), ('travel_ground', 'Business Travel — Ground'), ('travel_rail', 'Business Travel — Rail'), ('upstream_goods', 'Upstream Transportation of Goods')], max_length=50)),
                ('fuel_type', models.CharField(blank=True, help_text="e.g. 'natural_gas', 'diesel', 'kerosene' — blank for electricity", max_length=100)),
                ('country', models.CharField(help_text="ISO 3166-1 alpha-2; 'XX' for global", max_length=2)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, help_text='null = still current', null=True)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('factor_unit', models.CharField(choices=[('kWh', 'Kilowatt-hours'), ('MWh', 'Megawatt-hours'), ('kg', 'Kilograms'), ('t', 'Metric Tonnes'), ('L', 'Litres'), ('m3', 'Cubic Metres'), ('km', 'Kilometres'), ('mi', 'Miles'), ('tCO2e', 'Tonnes CO2-equivalent')], help_text='The denominator unit: kgCO2e per [this unit]', max_length=20)),
                ('source', models.CharField(help_text="e.g. 'GHG Protocol 2023', 'DEFRA 2024', 'Custom PPA contract'", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='null = global default; set to override for this tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_flat_file', 'SAP Flat-File Export (IDoc/ME2N)'), ('utility_csv', 'Utility Portal CSV Export'), ('travel_csv', 'Corporate Travel CSV (Concur/Navan)'), ('travel_json', 'Corporate Travel JSON (Concur/Navan)'), ('manual', 'Manual Entry')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('partial', 'Partial (some rows failed)'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=512)),
                ('file_path', models.CharField(blank=True, help_text='S3 or GCS path', max_length=1024)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 of raw file', max_length=64)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('flagged_rows', models.PositiveIntegerField(default=0)),
                ('parse_errors', models.JSONField(default=list, help_text='List of {row, field, raw_value, error} dicts for rows that could not be parsed at all (no RawRecord created).')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_jobs', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.PositiveIntegerField(help_text='0-based row number in source file')),
                ('raw_data', models.JSONField(help_text='Full row as parsed, keys preserved from source')),
                ('normalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.ingestionjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['ingestion_job', 'row_index'],
            },
        ),
        migrations.CreateModel(
            name='PlantSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sap_code', models.CharField(help_text='Exact plant code from SAP export', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_sites', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 — Direct'), ('2', 'Scope 2 — Indirect Energy'), ('3', 'Scope 3 — Value Chain')], max_length=1)),
                ('category', models.CharField(choices=[('fuel_stationary', 'Fuel — Stationary Combustion'), ('fuel_mobile', 'Fuel — Mobile Combustion'), ('procurement', 'Procurement (non-energy goods)'), ('electricity', 'Purchased Electricity'), ('heat_steam', 'Purchased Heat / Steam'), ('travel_air', 'Business Travel — Air'), ('travel_hotel', 'Business Travel — Hotel'), ('travel_ground', 'Business Travel — Ground'), ('travel_rail', 'Business Travel — Rail'), ('upstream_goods', 'Upstream Transportation of Goods')], max_length=50)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('location_raw', models.CharField(blank=True, help_text='Raw location string from source before lookup (plant code, address, etc.)', max_length=512)),
                ('period_start', models.DateField(help_text='Start of the activity or billing period (inclusive)')),
                ('period_end', models.DateField(help_text='End of the activity or billing period (inclusive)')),
                ('invoice_date', models.DateField(blank=True, help_text='Date on the invoice/bill if available', null=True)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(help_text='Unit as it appeared in the source file', max_length=20)),
                ('original_currency', models.CharField(blank=True, help_text='ISO 4217 if cost data present', max_length=3)),
                ('original_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('quantity_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized energy quantity in kWh', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized mass quantity in kg (fuel, goods)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_km', models.DecimalField(blank=True, decimal_places=4, help_text='Normalized distance in km (travel legs)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_nights', models.PositiveIntegerField(blank=True, help_text='Number of hotel nights (travel_hotel category only)', null=True)),
                ('distance_method', models.CharField(blank=True, choices=[('provided', 'Provided by source'), ('great_circle', 'Computed via great-circle (airport codes)'), ('lookup_table', 'Looked up from airport distance table')], help_text='Only set for travel_air and travel_ground records', max_length=50)),
                ('co2e_tonnes', models.DecimalField(blank=True, decimal_places=6, help_text='Computed: quantity × factor, in tCO2e. Null until factor resolved.', max_digits=18, null=True)),
                ('co2e_calculation_notes', models.TextField(blank=True, help_text='Free-text explanation of any non-standard calculation step')),
                ('travel_origin', models.CharField(blank=True, help_text='IATA code or city', max_length=10)),
                ('travel_destination', models.CharField(blank=True, help_text='IATA code or city', max_length=10)),
                ('travel_class', models.CharField(blank=True, choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First'), ('unknown', 'Unknown')], max_length=20)),
                ('vehicle_type', models.CharField(blank=True, help_text='Car rental type, rail operator, etc.', max_length=100)),
                ('traveller_count', models.PositiveSmallIntegerField(default=1)),
                ('sap_document_number', models.CharField(blank=True, help_text='SAP document / PO number', max_length=50)),
                ('sap_material_code', models.CharField(blank=True, help_text='SAP material/service code', max_length=50)),
                ('fuel_type', models.CharField(blank=True, help_text='e.g. diesel, natural_gas, LPG', max_length=100)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('meter_id', models.CharField(blank=True, max_length=100)),
                ('tariff_code', models.CharField(blank=True, max_length=100)),
                ('is_estimated_read', models.BooleanField(help_text='True if utility marked this as an estimated (not actual) meter read', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged — Needs Attention'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], db_index=True, default='pending', max_length=20)),
                ('flags', models.JSONField(blank=True, default=list, help_text='List of active flag codes on this record')),
                ('flag_notes', models.TextField(blank=True, help_text='Human-readable explanation for any flags (auto-populated or analyst-written)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emission_factor', models.ForeignKey(blank=True, help_text='Factor used for co2e calculation; null if MISSING_FACTOR flag set', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='ingestion.emissionfactor')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('plant_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.plantsite')),
                ('raw_record', models.OneToOneField(help_text='The exact source row this was derived from', on_delete=django.db.models.deletion.PROTECT, related_name='normalized_record', to='ingestion.rawrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-period_start', 'category'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('field_edit', 'Field value edited'), ('status_change', 'Status changed'), ('flagged', 'Record flagged'), ('flag_cleared', 'Flag cleared'), ('approved', 'Record approved'), ('locked', 'Record locked for audit'), ('unlocked', 'Record unlocked (superuser)'), ('factor_rerun', 'Emission factor recalculated')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Analyst explanation for manual changes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(help_text='The record this entry pertains to', on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='ingestion.normalizedrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddIndex(
            model_name='rawrecord',
            index=models.Index(fields=['tenant', 'ingestion_job'], name='ingestion_r_tenant__97e6ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('ingestion_job', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='plantsite',
            index=models.Index(fields=['tenant', 'sap_code'], name='ingestion_p_tenant__5cf363_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plantsite',
            unique_together={('tenant', 'sap_code')},
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'scope', 'period_start'], name='ingestion_n_tenant__b4d91a_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'category'], name='ingestion_n_tenant__f770cd_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_n_tenant__012efe_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['tenant', 'period_start', 'period_end'], name='ingestion_n_tenant__93dac4_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedrecord',
            index=models.Index(fields=['meter_id'], name='ingestion_n_meter_i_adccc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='normalizedrecord',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='period_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'source_type'], name='ingestion_i_tenant__8a39b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_i_tenant__93cd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['file_hash'], name='ingestion_i_file_ha_e9c0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['category', 'country', 'valid_from'], name='ingestion_e_categor_c8583d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['tenant', 'category'], name='ingestion_e_tenant__2928aa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['tenant', 'record', 'timestamp'], name='ingestion_a_tenant__ea0b88_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['tenant', 'changed_by'], name='ingestion_a_tenant__f904ec_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'username'], name='ingestion_u_tenant__46f3ea_idx'),
        ),
    ]
